apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-server:latest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-server:latest
  template:
    metadata:
      labels:
        app: httpd-server:latest
    spec:
      containers:
        - name: httpd-server:latest
          image: docker.io/beauclairbytes/httpd-server:latest
          ports:
            - containerPort: 80
