name: CI to public-k8s
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      # ---------- CI ----------
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: beauclairbytes/httpd-server:latest
      # ---------- CD ----------
      - name: Set up kubectl
        uses: Azure/setup-kubectl@v4

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Test oc
        run: oc version --client

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token:      ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Apply manifests
        run: |
          oc apply -f k8s/
      - name: Force rollout
        run: oc rollout restart deployment/httpd-server-deployment