name: CI to public-k8s
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      # ---------- CI ----------
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            beauclairbytes/httpd-server:latest
            beauclairbytes/httpd-server:${{ github.sha }}

      # ---------- CD ----------
      - name: Set up kubectl
        uses: Azure/setup-kubectl@v4

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Test oc
        run: oc version --client

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token:      ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Set IMAGE_TAG env variable
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Update Deployment YAML with Image Tag
        run: |
          sed -i "s|beauclairbytes/httpd-server:.*|beauclairbytes/httpd-server:${IMAGE_TAG}|g" k8s/deployment.yaml

      - name: Apply manifests
        run: |
          oc apply -f k8s/
          oc rollout status deployment/httpd-server-deployment
  # Downloads the content of the server and compares it with the index.html file
  test-server-content:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token:      ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Get Route URL
        id: get-url
        run: |
          ROUTE_URL=$(oc get route httpd-route -o jsonpath='http://{.spec.host}{.spec.path}')
          echo "ROUTE_URL=$ROUTE_URL" >> $GITHUB_ENV

      - name: Fetch Deployed HTML
        run: |
          curl -s $ROUTE_URL > deployed.html

      - name: Compare HTML with Reference
        run: |
          diff -q deployed.html src/index.html