name: CI to public-k8s
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      # ---------- CI ----------
      - uses: actions/checkout@v4

    #   - name: Run (dummy) tests
    #     run: echo "✓ unit tests"

    #   - name: Build & push image
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       push: true
    #       tags: ${{ env.REGISTRY }}:${{ github.sha }}

      # ---------- CD ----------
      - name: Set up kubectl
        uses: Azure/setup-kubectl@v4

      - name: Decode kubeconfig
        run: |
          mkdir -p "$HOME/.kube" 
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods                   # your Deployment, Service, Ingress YAML
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
